ATTR_V		:= 2.5.2
ATTR_FILE	:= attr-$(ATTR_V).tar.xz
BASH_V		:= 5.2.37
BASH_FILE	:= bash-$(BASH_V).tar.gz
BINUTILS_V	:= 2.44
BINUTILS_FILE	:= binutils-$(BINUTILS_V).tar.xz
BUSYBOX_V	:= 1.37.0
BUSYBOX_FILE	:= busybox-$(BUSYBOX_V).tar.bz2
HWLOC_V		:= 2.12.2
HWLOC_FILE	:= hwloc-$(HWLOC_V).tar.bz2
LINUX_V		:= 6.16.7
LINUX_FILE	:= linux-$(LINUX_V).tar.xz
LLVM_V		:= 20.1.8
LLVM_FILE	:= llvmorg-$(LLVM_V).tar.gz
MAKE_V		:= 4.4.1
MAKE_FILE	:= make-$(MAKE_V).tar.gz
MOLD_V		:= 2.40.4
MOLD_FILE	:= mold-$(MOLD_V).tar.gz
MUSL_V		:= 1.2.5
MUSL_FILE	:= musl-$(MUSL_V).tar.gz
NCURSES_V	:= 6.5
NCURSES_FILE	:= ncurses-$(NCURSES_V).tar.gz
ONETBB_V	:= 2022.0.0
ONETBB_FILE	:= onetbb-$(ONETBB_V).tar.gz
OPENSSL_V	:= 3.5.2
OPENSSL_FILE	:= openssl-$(OPENSSL_V).tar.gz
PKGCONF_V	:= 2.5.1
PKGCONF_FILE	:= pkgconf-$(PKGCONF_V).tar.gz
READLINE_V	:= 8.3
READLINE_FILE	:= readline-$(READLINE_V).tar.gz
UCONTEXT_V	:= 1.3.2
UCONTEXT_FILE	:= libucontext-$(UCONTEXT_V).tar.xz
XCRYPT_V	:= 4.4.38
XCRYPT_FILE	:= libxcrypt-$(XCRYPT_V).tar.xz
ZLIB_NG_V	:= 2.2.5
ZLIB_NG_FILE	:= zlib-ng-$(ZLIB_NG_V).tar.gz
ZSTD_V		:= 1.5.7
ZSTD_FILE	:= zstd-$(ZSTD_V).tar.gz

ATTR_URL	:= https://download.savannah.gnu.org/releases/attr/$(ATTR_FILE)
BASH_URL	:= http://ftpmirror.gnu.org/gnu/bash/$(BASH_FILE)
BINUTILS_URL	:= https://ftpmirror.gnu.org/gnu/binutils/$(BINUTILS_FILE)
BUSYBOX_URL	:= https://www.busybox.net/downloads/$(BUSYBOX_FILE)
HWLOC_URL	:= https://www.open-mpi.org/software/hwloc/v$(basename $(HWLOC_V))/downloads/$(HWLOC_FILE)
LINUX_URL	:= https://cdn.kernel.org/pub/linux/kernel/v6.x/$(LINUX_FILE)
LLVM_URL	:= https://github.com/llvm/llvm-project/archive/refs/tags/$(LLVM_FILE)
MAKE_URL	:= http://ftpmirror.gnu.org/gnu/make/$(MAKE_FILE)
MOLD_URL	:= https://github.com/rui314/mold/archive/refs/tags/v$(MOLD_V).tar.gz
MUSL_URL	:= http://www.etalabs.net/musl/releases/$(MUSL_FILE)
NCURSES_URL	:= http://ftpmirror.gnu.org/gnu/ncurses/$(NCURSES_FILE)
ONETBB_URL	:= https://github.com/uxlfoundation/oneTBB/archive/v$(ONETBB_V)/$(ONETBB_FILE)
OPENSSL_URL	:= https://github.com/openssl/openssl/releases/download/openssl-$(OPENSSL_V)/$(OPENSSL_FILE)
PKGCONF_URL	:= https://github.com/pkgconf/pkgconf/archive/refs/tags/$(PKGCONF_FILE)
READLINE_URL	:= http://ftpmirror.gnu.org/gnu/readline/$(READLINE_FILE)
UCONTEXT_URL	:= https://distfiles.dereferenced.org/libucontext/$(UCONTEXT_FILE)
XCRYPT_URL	:= https://github.com/besser82/libxcrypt/releases/download/v$(XCRYPT_V)/$(XCRYPT_FILE)
ZLIB_NG_URL	:= https://github.com/zlib-ng/zlib-ng/archive/refs/tags/$(ZLIB_NG_V).tar.gz
ZSTD_URL	:= https://github.com/facebook/zstd/releases/download/v$(ZSTD_V)/$(ZSTD_FILE)

$W/%.download:
	curl -L $($(*F)_URL) -o $W/$($(*F)_FILE)
	$(call done)
